"""add project generation to messages

Revision ID: ac2b6b1009dc
Revises: aab38d9a1d32
Create Date: 2026-07-30 17:19:38.010840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2b6b1009dc'
down_revision: Union[str, None] = 'aab38d9a1d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_items_id', table_name='memory_items')
    op.drop_table('memory_items')
    op.add_column('messages', sa.Column('preview_url', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('zip_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'zip_url')
    op.drop_column('messages', 'preview_url')
    op.create_table('memory_items',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='memory_items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='memory_items_pkey')
    )
    op.create_index('ix_memory_items_id', 'memory_items', ['id'], unique=False)
    # ### end Alembic commands ###
